name: Flutter Windows Build with Caching

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: actions/cache@v4
        id: cache-pub
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
      - run: flutter pub get
        if: steps.cache-pub.outputs.cache-hit != 'true'
      - run: flutter build windows --release
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: .\build\windows\x64\runner\Release\
          if-no-files-found: error
          compression-level: 9